In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Housing.csv')
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [3]:
x = df.iloc[:,1:]
x

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [4]:
y = df.iloc[:,0]
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 69.2 KB

In [6]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [7]:
nums_col= x.iloc[:, [0,1, 2, 3, 9]]
nums_col

     area  bedrooms  bathrooms  stories  parking
0    7420         4          2        3        2
1    8960         4          4        4        3
2    9960         3          2        2        2
3    7500         4          2        2        3
4    7420         4          1        2        2
..    ...       ...        ...      ...      ...
540  3000         2          1        1        2
541  2400         3          1        1        0
542  3620         2          1        1        0
543  2910         3          1        1        0
544  3850         3          1        2        0

[545 rows x 5 columns]

In [8]:
str_column = x.iloc[:,[4,5,6,7,8,10]]
str_column

    mainroad guestroom basement hotwaterheating airconditioning prefarea
0        yes        no       no              no             yes      yes
1        yes        no       no              no             yes       no
2        yes        no      yes              no              no      yes
3        yes        no      yes              no             yes      yes
4        yes       yes      yes              no             yes       no
..       ...       ...      ...             ...             ...      ...
540      yes        no      yes              no              no       no
541       no        no       no              no              no       no
542      yes        no       no              no              no       no
543       no        no       no              no              no       no
544      yes        no       no              no              no       no

[545 rows x 6 columns]

In [9]:
le = LabelEncoder()

for col in str_column:
    str_column[col] = le.fit_transform(str_column[col])

str_column

     mainroad  guestroom  basement  hotwaterheating  airconditioning  prefarea
0           1          0         0                0                1         1
1           1          0         0                0                1         0
2           1          0         1                0                0         1
3           1          0         1                0                1         1
4           1          1         1                0                1         0
..        ...        ...       ...              ...              ...       ...
540         1          0         1                0                0         0
541         0          0         0                0                0         0
542         1          0         0                0                0         0
543         0          0         0                0                0         0
544         1          0         0                0                0         0

[545 rows x 6 columns]

In [10]:
X = pd.concat([nums_col, str_column], axis=1)
X

,area,bedrooms,bathrooms,stories,parking,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea
0,7420,4,2,3,2,1,0,0,0,1,1
1,8960,4,4,4,3,1,0,0,0,1,0
2,9960,3,2,2,2,1,0,1,0,0,1
3,7500,4,2,2,3,1,0,1,0,1,1
4,7420,4,1,2,2,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,2,1,0,1,0,0,0
541,2400,3,1,1,0,0,0,0,0,0,0
542,3620,2,1,1,0,1,0,0,0,0,0
543,2910,3,1,1,0,0,0,0,0,0,0
544,3850,3,1,2,0,1,0,0,0,0,0

In [11]:
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [12]:
# Now we are ready with our dataset
X_train,X_test,y_train , y_test = train_test_split(X ,y,test_size = 0.2,random_state = 41)
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((436, 11), (109, 11), (436,), (109,))

In [13]:
X_train

,area,bedrooms,bathrooms,stories,parking,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea
29,5500,4,2,2,1,1,0,1,0,1,1
16,6600,4,2,2,1,1,1,1,0,1,1
110,6600,3,1,1,2,1,1,1,0,0,1
446,3986,2,2,1,1,0,1,1,0,0,0
223,6321,3,1,2,1,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
469,4600,2,1,1,0,1,0,0,0,0,0
407,2145,3,1,3,0,1,0,0,0,0,1
243,2550,3,1,2,0,1,0,1,0,0,0
321,3630,3,2,2,2,1,0,0,1,0,0
80,6000,3,1,2,1,1,0,0,1,0,1

In [14]:
model = LinearRegression()
model.fit(X_train,y_train)
model

LinearRegression()

In [15]:
y_pred = model.predict(X_test)
y_pred

array([2942717.36103036, 4112455.46564894, 3569644.91787695,
       6763116.92648259, 2707318.46678973, 5363684.18252837,
       5034737.31012778, 4355987.17155912, 5440052.86096299,
       3331478.56471953, 3191616.32945403, 6408484.41973655,
       2679943.02389807, 3537749.75366943, 3384516.16124888,
       2953697.45281465, 3489736.88078458, 6294161.39182835,
       3364329.09618951, 5456402.06436654, 3781242.52128751,
       3650248.25381219, 4416089.4481126 , 4297841.46765645,
       3145107.99116584, 3536764.47177933, 5794327.23973865,
       3965929.72021486, 3879576.55380706, 8104344.52319252,
       2570331.51650587, 2827770.41551303, 2378485.85437386,
       5812745.25056398, 6455317.45951399, 7760319.06215516,
       2715531.09965723, 6678942.10308403, 5428307.98670036,
       3331627.61498483, 4346559.52388433, 5025655.29354917,
       3654291.22895067, 3411534.39179693, 4166212.01102467,
       3668618.21249131, 3815776.42738382, 7921728.51232873,
       6038481.68076888, 6355700.61680712, 7529194.20366818,
       5081976.59330118, 2803550.20946247, 3243659.58557581,
       4208886.68803013, 6823272.22211568, 2718268.64394639,
       4434490.88810506, 5814485.37085893, 6708366.04069928,
       5390276.00006295, 4089337.92168326, 5823886.07982375,
       4757056.53907602, 5549962.03856534, 3363346.75182077,
       3012240.05254997, 3977895.53011085, 3619727.40822673,
       6113435.04138313, 3670975.96724254, 6990887.39168093,
       6937191.40074431, 8371274.9070063 , 6488234.13732112,
       3666067.19277733, 3825043.22991416, 3512305.53806977,
       7086277.39665497, 4510651.10015228, 4470638.64374882,
       3640161.94980414, 3943755.61147262, 6051033.34916164,
       7536745.89533403, 3712539.15414714, 5897115.7299776 ,
       5556772.80815154, 5432240.13759771, 7079913.82779014,
       6293942.68337241, 4148432.08002919, 3895454.59895413,
       2570331.51650587, 4775824.69063106, 3629912.80290505,
       3679097.99343858, 7659649.07032338, 2816820.23835636,
       4051235.15087971, 3925525.6754685 , 5561712.70410769,
       3195298.30758046, 6237431.91400639, 3275014.38968225,
       3918603.20411296, 4248007.92947436, 5990111.00296144,
       4504541.47126003])

In [16]:
# Now we use the evaluation metrics to check how accurate the prediction of our it is
print(f'The R2_score of model is : {r2_score(y_test,y_pred)}')
print(f'The Mean Squared Error of model  is : {mean_squared_error(y_test,y_pred)}')
print(f'Root Mean Squared Error of model is :{np.sqrt(mean_squared_error(y_test, y_pred))}')

The R2_score of model is : 0.5919214673068186
The Mean Squared Error of model  is : 1301842405823.04
Root Mean Squared Error of model is :1140983.0874395291